module.exports = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means the current docs folder
    },
  ],
  // what: [
  //   {
  //     type: 'category',
  //     label: 'What is Tantra sceptic ?',
  //     items: [
  //       'what/what-is-tantra',
  //       'what/what-is-new-age',
  //     ],
  //   },
  // ],
  // docs: [
  //   {
  //     type: 'category',
  //     label: 'Docusaurus Tutorial',
  //     items: [
  //       'getting-started',
  //       'create-a-page',
  //       'create-a-document',
  //       'create-a-blog-post',
  //       'markdown-features',
  //       'thank-you',
  //     ],
  //   },
  // ],
};
